spring:
  application:
    name: MakerSpaceTools

data:
  coworker:
    id: 1421163984
  embroidery-machine:
      guid: 26d120e1-4fac-4c8b-a24f-87a8fbf1406f
      id: 1414834170

automation:
  jobs-file: data/auto-booking-jobs.json
  scheduler-delay: PT1M
  attempt-interval: PT5M
  feed-size: 200

makerspace:
  base-url: https://makerspace.spaces.nexudus.com
  auth:
    username: ${MAKERSPACE_USERNAME:example.email@mail.com}
    password: ${MAKERSPACE_PASSWORD:example_secret_password}
    client-id: ${MAKERSPACE_CLIENT_ID:nexudus.portal.example.email@mail.com}
    totp: ${MAKERSPACE_TOTP}
